version: '3'

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - "5080:5080"  # HTTP API
    environment:
      - ZO_DATA_DIR=/data
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
    volumes:
      - ./data:/data  # Adjust path as needed

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports: 
      - "4317:4317"
      - "4318:4318"  
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-config.yaml
      - ./logs:/logs 
    command: ["--config", "/etc/otel-config.yaml"]
    depends_on:
      - openobserve
