receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default
    headers:
      Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM= # default password
      stream-name: default

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/openobserve]

    # metrics:
    #   receivers: [filelog]
    #   processors: [batch]
    #   exporters: [otlphttp/openobserve]
  # endpoint: "0.0.0.0:4318"
        # endpoint: "0.0.0.0:4317"